from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from core.config import get_paths


def count_jsonl(path: Path) -> int:
    if not path.exists():
        return 0
    with path.open("r", encoding="utf-8") as fh:
        return sum(1 for line in fh if line.strip())


def load_json(path: Path) -> object:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    paths = get_paths(ROOT)
    report = {
        "icd10": {
            "status": load_json(paths.data_processed / "icd10" / "status.json"),
            "concept_rows": count_jsonl(paths.data_processed / "icd10" / "icd10_concepts.jsonl"),
        },
        "rxnorm": {
            "status": load_json(paths.data_processed / "rxnorm" / "status.json"),
            "concept_rows": count_jsonl(paths.data_processed / "rxnorm" / "rxnorm_concepts.jsonl"),
        },
        "public_corpora": load_json(paths.data_raw / "public_corpora" / "status.json"),
        "vi_aliases": {
            "aliases": count_jsonl(paths.data_processed / "vi_aliases" / "aliases.jsonl"),
            "diseases": count_jsonl(paths.data_processed / "vi_aliases" / "disease_aliases.jsonl"),
            "drugs": count_jsonl(paths.data_processed / "vi_aliases" / "drug_aliases.jsonl"),
            "symptoms": count_jsonl(paths.data_processed / "vi_aliases" / "symptom_aliases.jsonl"),
            "labs": count_jsonl(paths.data_processed / "vi_aliases" / "lab_aliases.jsonl"),
        },
        "kb": {
            "concepts": count_jsonl(paths.data_processed / "concepts.jsonl"),
            "aliases": count_jsonl(paths.data_processed / "aliases.jsonl"),
        },
        "indexes": {
            "ontology_index": (paths.data_indexes / "ontology_index.json").exists(),
            "alias_exact": (paths.data_indexes / "alias_exact.json").exists(),
            "alias_norm": (paths.data_indexes / "alias_norm.json").exists(),
            "manifest": load_json(paths.data_indexes / "kb_manifest.json"),
        },
    }
    inventory = [
        "# Data Inventory",
        "",
        "This report is generated by `python scripts/inspect_data_status.py`.",
        "",
        "```json",
        json.dumps(report, ensure_ascii=False, indent=2),
        "```",
        "",
        "Restricted/manual resources: UMLS and MIMIC-style clinical notes are not downloaded automatically and require separate credentials/licenses.",
    ]
    docs_path = paths.root / "docs" / "data_inventory.md"
    docs_path.parent.mkdir(parents=True, exist_ok=True)
    docs_path.write_text("\n".join(inventory), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
